### ISSUE TITLE
Download failed:  <urlopen error [Errno 113] No route to host> 

### ISSUE THREAD

**Issue by learning4life** [carlodef/rpc_cropper#1]
When trying to access the needed srtm tiles:  set(['srtm_59_08']) the error "Download failed:  <urlopen error [Errno 113] No route to host>"  is reported.

I tried multiple times using different imagery/locations.

**Comment by carlodef** [comment]
Thank you for reporting this issue. The url of the SRTM mirror was outdated. It's fixed.
